spring.application.name=PruebaEdwslme

server.port=8081

# URL en memoria
spring.datasource.url=jdbc:h2:mem:prueba_db;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Dialecto JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
# Mostrar SQL (opcional)
spring.jpa.show-sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
springdoc.swagger-ui.path=/api/docs
springdoc.api-docs.enabled=true
logging.level.org.springdoc=DEBUG
logging.level.org.springframework.web=DEBUG
soap.flag.success=true